export const categories = [
  { id: 'smartphones', name: 'Smartphones', icon: 'smartphone' },
  { id: 'laptops', name: 'Laptops', icon: 'laptop' },
  { id: 'tablets', name: 'Tablets', icon: 'tablet' },
  { id: 'accessories', name: 'Accessories', icon: 'headphones' },
];

export const moroccanCities = [
  { id: 'casablanca', name: 'Casablanca' },
  { id: 'rabat', name: 'Rabat' },
  { id: 'marrakech', name: 'Marrakech' },
  { id: 'fes', name: 'Fès' },
  { id: 'tangier', name: 'Tanger' },
  { id: 'agadir', name: 'Agadir' },
  { id: 'meknes', name: 'Meknès' },
  { id: 'oujda', name: 'Oujda' },
  { id: 'kenitra', name: 'Kénitra' },
  { id: 'tetouan', name: 'Tétouan' },
  { id: 'safi', name: 'Safi' },
  { id: 'mohammedia', name: 'Mohammedia' },
  { id: 'eljadida', name: 'El Jadida' },
  { id: 'khouribga', name: 'Khouribga' },
  { id: 'beniMellal', name: 'Béni Mellal' },
  { id: 'taza', name: 'Taza' },
  { id: 'khemisset', name: 'Khémisset' },
  { id: 'taourirt', name: 'Taourirt' },
  { id: 'essaouira', name: 'Essaouira' },
  { id: 'asilah', name: 'Asilah' },
  { id: 'tinghir', name: 'Tinghir' },
  { id: 'ouarzazate', name: 'Ouarzazate' },
  { id: 'larache', name: 'Larache' },
  { id: 'guelmim', name: 'Guelmim' },
  { id: 'ifrane', name: 'Ifrane' },
  { id: 'chefchaouen', name: 'Chefchaouen' },
  { id: 'nador', name: 'Nador' },
  { id: 'settat', name: 'Settat' },
  { id: 'taroudant', name: 'Taroudant' },
  { id: 'errachidia', name: 'Errachidia' }
];

export const products = [
  {
    id: '1',
    name: 'iPhone 13',
    description: 'The latest iPhone with a super-fast chip and amazing camera.',
    price: 999,
    images: [
      'https://images.unsplash.com/photo-1638913660107-99ca86c934a9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGlwaG9uZXxlbnwwfHwwfHx8MA%3D%3D',
      'https://images.unsplash.com/photo-1614850740534-49368a936951?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGlwaG9uZXxlbnwwfHwwfHx8MA%3D%3D',
      'https://images.unsplash.com/photo-1512054502232-9a3e5134d668?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGlwaG9uZXxlbnwwfHwwfHx8MA%3D%3D',
    ],
    category: 'smartphones',
    rating: 4.8,
    stock: 50,
    sku: 'IP13-128',
    featured: true,
    onSale: true,
    oldPrice: 1200,
  },
  {
    id: '2',
    name: 'Samsung Galaxy S21',
    description: 'A powerful Android phone with a stunning display.',
    price: 899,
    images: [
      'https://images.unsplash.com/photo-1610792974439-1c95a54f5019?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHNhbXN1bmclMjBwaG9uZXxlbnwwfHwwfHx8MA%3D%3D',
      'https://images.unsplash.com/photo-1617171189845-45957694156a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTUxfHxzYW1zdW5nJTIwcGhvbmV8ZW58MHx8MHx8fDA%3D',
    ],
    category: 'smartphones',
    rating: 4.5,
    stock: 30,
    sku: 'SG21-256',
    featured: false,
    onSale: false,
  },
  {
    id: '3',
    name: 'Dell XPS 13',
    description: 'A premium laptop with a sleek design and powerful performance.',
    price: 1299,
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1b5cb5e8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bGFwdG9wfGVufDB8fDB8fHww',
      'https://images.unsplash.com/photo-1543528283-9be7996764c4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxhcHRvcHxlbnwwfHwwfHx8MA%3D%3D',
    ],
    category: 'laptops',
    rating: 4.7,
    stock: 20,
    sku: 'DXPS13-512',
    featured: true,
    onSale: false,
  },
  {
    id: '4',
    name: 'iPad Pro',
    description: 'The ultimate tablet experience with a stunning display and powerful chip.',
    price: 799,
    images: [
      'https://images.unsplash.com/photo-1549831243-a69a0b3d8ca9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aXBhZHxlbnwwfHwwfHx8MA%3D%3D',
      'https://images.unsplash.com/photo-1563245377-b537c5c4a38f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aXBhZHxlbnwwfHwwfHx8MA%3D%3D',
    ],
    category: 'tablets',
    rating: 4.6,
    stock: 40,
    sku: 'IPAD-256',
    featured: false,
    onSale: true,
    oldPrice: 900,
  },
];
